C*    COMMON *YOETHF* DERIVED CONSTANTS SPECIFIC TO ECMWF THERMODYNAMICS
C
C     *R__ES*   *CONSTANTS USED FOR COMPUTATION OF SATURATION
C                MIXING RATIO OVER LIQUID WATER(*R_LES*) OR
C                ICE(*R_IES*).
C     *RVTMP2*  *RVTMP2=RCPV/RCPD-1.
C     *RHOH2O*  *DENSITY OF LIQUID WATER.   (RATM/100.)
C
      REAL R2ES, R3LES, R3IES, R4LES, R4IES, R5LES, R5IES
      REAL RVTMP2, RHOH2O
      COMMON /YOETHF/R2ES, R3LES, R3IES, R4LES, R4IES, R5LES, R5IES,
     .               RVTMP2, RHOH2O
