#!/bin/bash


pidfile='./log/rc_model.pid'


if [ -a $pidfile ]; then
   echo "ensuring old server is killed"
   pid=`cat  $pidfile`
   pkill -P $pid >& /dev/null || true
   kill $pid >& /dev/null || true

fi



